apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traffipi
resources:
  - namespace.yaml
  - api-deployment.yaml
  - web-deployment.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: traffipi
    includeSelectors: false
